"""Gambar untuk diperiksa mata: kokpit hujan dan kabut, langkah 3 dan 8, malam dari atas, kejar di awal, ponsel manual."""
import time
from sim3d_fix_common import *  # noqa

with sync_playwright() as p:
    b = launch(p)
    ctx, page, log = new_page(b)
    open_sim(page, "tutorial")
    time.sleep(0.5)
    ev(page, "() => window.__app.tutorial.go(2)")
    time.sleep(1.5)
    shot(page, "vis_step3_kejar.png")
    ev(page, "() => window.__app.tutorial.go(7)")
    time.sleep(4)
    shot(page, "vis_step8.png")
    ev(page, "() => window.__app.setMode('bebas')")
    for wx, cam in (("hujan", "kokpit"), ("kabut", "kokpit"), ("malam", "atas"), ("hujan", "kejar"), ("cerah", "kokpit")):
        ev(page, f"() => {{ window.__app.setWeather('{wx}'); window.__app.setCamera('{cam}', {{ reset: true }}); }}")
        time.sleep(2)
        shot(page, f"vis_{wx}_{cam}.png")
    ev(page, "() => { window.__app.setWeather('cerah'); window.__app.setQuality('hemat'); window.__app.setCamera('kejar', { reset: true }); }")
    time.sleep(1.5)
    shot(page, "vis_hemat_kejar.png")
    print("hemat", snap(page)["render"])
    ctx.close()
    ctx, page, log2 = new_page(b, mobile=True)
    open_sim(page, "bebas")
    time.sleep(1)
    page.tap(".s3d-tab[data-tab=kontrol]")
    time.sleep(0.3)
    page.tap(".s3d-switch")
    time.sleep(0.8)
    shot(page, "vis_m_manual.png")
    print("toasts", ev(page, "() => [...document.querySelectorAll('.s3d-toast')].map(t => t.textContent)"))
    page.tap(".s3d-tab[data-tab=uji]")
    time.sleep(0.4)
    shot(page, "vis_m_uji.png")
    print("LOG", log, log2)
    b.close()
